// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLBTDNyTIUf4n3IrlqNFi2se6ENVnlBMY',
    appId: '1:668939904060:web:a34c8cb3e00b3a14928f39',
    messagingSenderId: '668939904060',
    projectId: 'todo-6675a',
    authDomain: 'todo-6675a.firebaseapp.com',
    storageBucket: 'todo-6675a.firebasestorage.app',
    measurementId: 'G-J475KTPCMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwi_BNWd0tnAbpwso37EZGiKvYZcAsz_c',
    appId: '1:668939904060:android:f4ed82d61ea55346928f39',
    messagingSenderId: '668939904060',
    projectId: 'todo-6675a',
    storageBucket: 'todo-6675a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1GRnRYmBD48F8XM8FlVnBn3jwItR2Jo',
    appId: '1:668939904060:ios:67121a0025a0204d928f39',
    messagingSenderId: '668939904060',
    projectId: 'todo-6675a',
    storageBucket: 'todo-6675a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ1GRnRYmBD48F8XM8FlVnBn3jwItR2Jo',
    appId: '1:668939904060:ios:67121a0025a0204d928f39',
    messagingSenderId: '668939904060',
    projectId: 'todo-6675a',
    storageBucket: 'todo-6675a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLBTDNyTIUf4n3IrlqNFi2se6ENVnlBMY',
    appId: '1:668939904060:web:f3744593a20ad64e928f39',
    messagingSenderId: '668939904060',
    projectId: 'todo-6675a',
    authDomain: 'todo-6675a.firebaseapp.com',
    storageBucket: 'todo-6675a.firebasestorage.app',
    measurementId: 'G-ETYTNVB8MN',
  );
}
