// GENERATED BY FLUTTERFIRE CLI
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔹 WEB CONFIG
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "YOUR_API_KEY",
    authDomain: "your-project.firebaseapp.com",
    projectId: "your-project-id",
    storageBucket: "your-project.appspot.com",
    messagingSenderId: "SENDER_ID",
    appId: "APP_ID",
  );

  // 🔹 ANDROID CONFIG
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "YOUR_API_KEY",
    appId: "APP_ID",
    messagingSenderId: "SENDER_ID",
    projectId: "your-project-id",
    storageBucket: "your-project.appspot.com",
  );

  // 🔹 IOS CONFIG
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "YOUR_API_KEY",
    appId: "APP_ID",
    messagingSenderId: "SENDER_ID",
    projectId: "your-project-id",
    storageBucket: "your-project.appspot.com",
    iosBundleId: "com.example.app",
  );

  // 🔹 MACOS (optional)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "YOUR_API_KEY",
    appId: "APP_ID",
    messagingSenderId: "SENDER_ID",
    projectId: "your-project-id",
    storageBucket: "your-project.appspot.com",
    iosBundleId: "com.example.app",
  );
}
